/*-------------------------------- FILE INFO ---------------------------------*/
/* Filename           : build_info.h                                          */
/*                                                                            */
/* Interface for micromouse build_info library                                */
/*                                                                            */
/*----------------------------------------------------------------------------*/
#ifndef BUILD_INFO_H_
#define BUILD_INFO_H_

/*----------------------------------------------------------------------------*/
/*                             Public Definitions                             */
/*----------------------------------------------------------------------------*/
struct build_repository {
    char const *name;
    char const *url;
    char const *commit;
};

/* variables defined by file generated by CMake using template */
extern char const *const build_date;
extern char const *const build_time;
extern char const *const build_configuration;
extern char const *const build_mouse_target;
extern const struct build_repository build_repositories[];
extern const uint32_t build_repository_count;

/*----------------------------------------------------------------------------*/
/*                         Public Function Prototypes                         */
/*----------------------------------------------------------------------------*/
struct command_node const *get_build_info_node(void);

enum validation_result validate_build(struct command *cmd);
void execute_build(struct command const *cmd);

#endif /* BUILD_INFO_H_ */
